name: linting

on: push

jobs: 
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['3.10', '3.9']
    steps: 
      - name: code checkout 
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.version }}

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8
        run: |
          flake8 app.py